#!/bin/bash

# Copyright 2022 Abhay Shanker Pathak

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# run the script after you have login with your account

[ -n "$1" ] \
	&& [ "--help" = "$1" ] \
	&& printf "USAGE: ./cseprac_pdfs [--help]\nPdfs saved at '/tmp/csepracticals_*_pdfs'\n" \
	&& exit 0

backup_ifs="${IFS}"
IFS=$'\n'

START_FILE="/tmp/csepracticals_teachable.html"
MAIN_URL="https://csepracticals.teachable.com"
START_URL="https://csepracticals.teachable.com/courses/1646555/lectures/37513156"
TMP_DIR_NAME="/tmp/csepracticals_$(date +%s)"
PDF_DIR_NAME="${TMP_DIR_NAME}_pdfs"

echo "Get initial file: ${START_FILE}"
[ ! -f "${START_FILE}" ] \
	&& curl -q "${START_URL}" 1> "${START_FILE}"

[ ! -f "${START_FILE}" ] \
	&& echo "Problem in downloading the webpage" \
	&& exit 1

mkdir -p "${TMP_DIR_NAME}"
echo "temp html dir: ${TMP_DIR_NAME}"

read -r -d '' -a course_ids < <( grep -ioE 'data-lecture-id="[0-9]*"' "${START_FILE}" \
	| cut -d\" -f2 && printf '\0' )

echo ""
echo "---------------"
echo ""

# I think there are some duplicate ids in this array
PG_PREFIX="/courses/only-resources/lectures/"
for id in "${course_ids[@]}"; do
	new_url="${MAIN_URL}${PG_PREFIX}${id}"
	echo "${new_url}"
	curl -q "${new_url}" 1> "${TMP_DIR_NAME}/${id}.html"
done

echo ""
echo "---------------"
echo ""

# delete old pdf files in there if any
[ -d "${PDF_DIR_NAME}" ] && rm -r "${PDF_DIR_NAME}"

mkdir -p "${PDF_DIR_NAME}"

echo "=> pdfs stored at: ${PDF_DIR_NAME}"
echo ""

for id in "${course_ids[@]}"; do
	new_html="${TMP_DIR_NAME}/${id}.html"
	echo "${new_html}"
	for res_str in $(grep -iE 'download-name=.*' ${new_html}); do
		pdf_name="$(echo ${res_str} \
			| grep -ioE 'download-name=.*' \
			| cut -d\' -f2)"
		pdf_url="$(echo ${res_str} | grep -ioE "href='https://cdn.*" \
			| cut -d' ' -f1 \
			| cut -d\' -f2)"
		echo "Downloading pdf: ${PDF_DIR_NAME}/${pdf_name}"
		curl -q "${pdf_url}" 1> "${PDF_DIR_NAME}/${pdf_name}"
		echo "---------------"
		echo ""
	done
done

echo "doing cleanup"
echo ""

rm -r "${START_FILE}" "${TMP_DIR_NAME}"

IFS="${backup_ifs}"

exit 0

# https://csepracticals.teachable.com/courses/only-resources/lecture/37513178 -O example.html
