#!/bin/sh

# Open man pages in pdfviewer using dmenu
# In my case it's zathura

getmanname() {
	man -k . \
		| dmenu -i -l 20 -c \
		| awk '{print $1}' | xargs -r man -Tpdf \
		| zathura -
}

getshufman() {
	getname=$(fd . --type f /usr/share/man/man1 \
		| shuf \
		| head -n 1)
	propername=$(basename "${getname}" \
		| sed 's/.1.gz//g')
	# xargs -r man -Tpdf "${propername}" \
	man -Tpdf "${propername}" \
	| zathura -
}

show_options() {
	get_choice=$(printf "%s\n%s\n" \
		"search - It will provide list of the various commands to get manual" \
		"shuf - It'll choose a random command and open it's manual" \
		| dmenu -l 20 -i -c)
		choice_is="$(echo "${get_choice}" | awk '{print $1}')"
}

show_options

case "$choice_is" in
	search) getmanname;;
	shuf) getshufman;;
esac
