#!/usr/bin/env bash

# bash4.0 and above

# add the dir name only to a file of your choice and give the filepath here
file_name="${HOME}/.cache/temp/exclude_pdf_dirs.txt"

ext_array=( "pdf" )  # provide extensions for videos to search

readarray -t excludedirs < "${file_name}"
exclude_args=()
find_extensions=()

for names in "${excludedirs[@]}"; do
	exclude_args+=("-E" "${names}")  # add -E(--exclude) flag
done

for ext in "${ext_array[@]}"; do
	find_extensions+=("-e" "${ext}")  # add -e(to search by file extension)
done

#fd . -u "${exclude_args[@]}" --type f "${find_extensions[@]}" "${HOME}/Documents" "${HOME}/Downloads"

(fd . -u "${exclude_args[@]}" --type f "${find_extensions[@]}" "${HOME}/Documents" "${HOME}/Downloads" - 0) | shuf | rofi -dmenu -lines 20 -i -matching fuzzy | xargs -I {} mpv "{}"



# old stuff

#fd . -u --type f -e pdf '/home/raytracer/Documents' '/home/raytracer/Downloads'

# find ~/Downloads ~/Documents -name "*.pdf" | rofi -dmenu -i -lines 20 -width 80 | xargs -I {} zathura "{}"
# fd . -u --type f -e pdf '/home/raytracer/Documents' '/home/raytracer/Downloads'| rofi -dmenu -i -lines 20 -width 80 | xargs -I {} zathura "{}"
