#!/usr/bin/env sh

#diff <(pacman -Q) <(pacman -Qn)

# add the dir name only to a file of your choice and give the filepath here
file_name="${HOME}/.cache/temp/exclude_pdf_dirs.txt"

ext_array=( "pdf" )  # provide extensions for videos to search

readarray -t excludedirs < "${file_name}"
exclude_args=()
find_extensions=()

for names in "${excludedirs[@]}"; do
	exclude_args+=("-E" "${names}")  # add -E(--exclude) flag
done

for ext in "${ext_array[@]}"; do
	find_extensions+=("-e" "${ext}")  # add -e(to search by file extension)
done

#fd . -u "${exclude_args[@]}" --type f "${find_extensions[@]}" "${HOME}/Documents" "${HOME}/Downloads"

(fd . -u "${exclude_args[@]}" --type f "${find_extensions[@]}" "${HOME}/Documents" "${HOME}/Downloads" ) | shuf | dmenu -l 20 -i -c | xargs -I {} zathura "{}"
