#!/bin/bash

path_from=""
path_to=""

echo "Enter path containg files/directories(No input will consider cwd): "
read -r path_from

if [ -z "${path_from}" ]; then
	path_from="$(pwd)"
fi


echo "Enter path to create new directory to put these sorted files/directories: "
echo "[entered path will be relative to current directory]"
read -r path_to
while [ -z "${path_to}" ]; do
	echo "Destination path not entered. Try again[press Ctrl-c to quit]"
	echo "Enter path to create new directory to put these sorted files/directories: "
	echo "[entered path will be relative to current directory]"
	read -r path_to
done

[ ! -d "${path_to}" ] && mkdir -p "${path_to}"


backup_IFS="${IFS}"
IFS=$'\n'

find_files=$(find ${path_from} -maxdepth 1 -type f -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg")

for name in ${find_files}; do
	[ ! -f "${name}" ] && continue
	res="$(identify -format "%wx%h\n" $(basename "${name}"))"
	width=$(echo "${res}" | cut -d'x' -f1)
	height=$(echo "${res}" | cut -d'x' -f2)
	#echo "width: ${width}, height: ${height}"
	printf "width: %5s, height: %5s" ${width} ${height}

	if [ "${height}" -gt "${width}" ]; then
		printf " [ moving: %s to %s ]" $(basename ${name}) ${path_to}
		mv "$name" "${path_to}"
	fi

	echo
done

find "${path_to}" -maxdepth 0 -empty -exec echo {} is empty. Removing the directory \; \
	&& rmdir "${path_to}" 2>/dev/null

IFS=${backup_IFS}
